module.exports = {
    NULL: 0,
    VARI_TRAINING_MODE: 1,
    GROUP_TRAINING_MODE: 2,
    OPENING_TRAINING_MODE: 3,
    COLOR_TRAINING_MODE: 4,
    SMART_TRAINING_MODE: 5,
    FREE_PLAYING_MODE: 6,
    NEW_VARI_MODE: 7,
    AGAINST_STOCKFISH_MODE: 8,
    SPECTATOR_MODE: 9,
}